### ISSUE TITLE
Version 0.23.4 does not load view of db collections

### ISSUE THREAD

**Issue by iTerminate** [andzdroid/mongo-express#119]
Version 0.23.3 works while 0.23.4 gives me an error when I try to load a view for a db collection. 

Error output: 
TypeError: Cannot read property 'this_would_be_my_collection_name' of undefined
   at exp.viewCollection (node_modules/mongo-express/routes/collection.js:30:52)
   at Layer.handle [as handle_request] (node_modules/mongo-express/node_modules/express/lib/router/layer.js:95:5)
   at next (node_modules/mongo-express/node_modules/express/lib/router/route.js:131:13)
   at mongoMiddleware (node_modules/mongo-express/router.js:157:5)
   at Layer.handle [as handle_request] (node_modules/mongo-express/node_modules/express/lib/router/layer.js:95:5)
   at next (node_modules/mongo-express/node_modules/express/lib/router/route.js:131:13)
   at Route.dispatch (node_modules/mongo-express/node_modules/express/lib/router/route.js:112:3)
   at Layer.handle [as handle_request] (node_modules/mongo-express/node_modules/express/lib/router/layer.js:95:5)
   at node_modules/mongo-express/node_modules/express/lib/router/index.js:277:22
   at param (node_modules/mongo-express/node_modules/express/lib/router/index.js:349:14)

**Comment by wulfsolter** [comment]
Fixed with https://github.com/andzdroid/mongo-express/pull/118
