### ISSUE TITLE
run node app.js error

### ISSUE THREAD

**Issue by jiujie395** [andzdroid/mongo-express#168]
/usr/local/node/lib/node_modules/mongo-express/app.js:16
let notifier          = updateNotifier({pkg});
                                           ^
SyntaxError: Unexpected token }
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by wulfsolter** [comment]
Update your version of Node and/or `$ npm install` ?

**Comment by jiujie395** [comment]
@wulfsolter  thanks ，update node laster version is ok...
