### ISSUE TITLE
Mongo Express throws SyntaxError on attempted delete of index

### ISSUE THREAD

**Issue by textbook** [andzdroid/mongo-express#169]
Clicking the red "X" button next to an entry in `system.indexes` resulted in the following:

```
SyntaxError: Unexpected token u
   at Object.parse (native)
   at /home/vcap/app/router.js:125:15
   at paramCallback (/home/vcap/app/node_modules/express/lib/router/index.js:404:7)
   at param (/home/vcap/app/node_modules/express/lib/router/index.js:384:5)
   at paramCallback (/home/vcap/app/node_modules/express/lib/router/index.js:401:21)
   at /home/vcap/app/router.js:119:7
   at Db.collection (/home/vcap/app/node_modules/mongodb/lib/db.js:423:20)
   at /home/vcap/app/router.js:111:35
   at paramCallback (/home/vcap/app/node_modules/express/lib/router/index.js:404:7)
   at param (/home/vcap/app/node_modules/express/lib/router/index.js:384:5)
```

If Mongo Express cannot delete an index then the button should be removed (or the error handled more gracefully), and if it can it appears that there's a bug.

**Comment by wulfsolter** [comment]
From the errors it looks like it could be an older version you're running. Can you update and let us know how that goes?

**Comment by textbook** [comment]
Having updated to the latest version, I now see simply `Internal Server Error`...

**Comment by wulfsolter** [comment]
So deleting indexes like this isn't the way to go so I removed that with https://github.com/andzdroid/mongo-express/commit/0393a96b65a8360db7a58efdcd854dbdeb0f06b6
 and also added better error messages if trying to delete something that lacks an _id https://github.com/andzdroid/mongo-express/commit/f893d9c616b854917e644ee452d6b024e4392e55 

Npm has been updated
