### ISSUE TITLE
fails to start

### ISSUE THREAD

**Issue by ScottChapman** [andzdroid/mongo-express#93]
Failed to load c++ bson extension, using pure JS version
connect.multipart() will be removed in connect 3.0
visit https://github.com/senchalabs/connect/wiki/Connect-3.0 for alternatives
connect.limit() will be removed in connect 3.0
Mongo Express server listening on port 8081
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EACCES
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1139:19)
    at listen (net.js:1182:10)
    at Server.listen (net.js:1267:5)
    at Function.app.listen (C:\node\mongo\node_modules\mongo-express\node_module
s\express\lib\application.js:533:24)
    at Object.<anonymous> (C:\node\mongo\node_modules\mongo-express\app.js:315:7
)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

**Comment by ambrosechua** [comment]
Port 8081 is used, go check
